name: "Jennifer Aldoretta"
description: "Jennifer Aldoretta is an Austin entrepreneur, graphic designer, web developer, artist, writer, and badass."

url: "http://localhost:4000"

encoding: "utf-8"
permalink: pretty
